= Docs Home
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-layout: landing
:lang: en

// This is the documentation site for https://decidim.org/{lang}[Decidim].
This is the documentation site for https://decidim.org[Decidim].

All our documents are published under the Creative Commons By-SA and the GNU Free Documentation licenses.
They are open to participation and can be forked.
See how to contribute to our documentation in our xref:{lang}@docs-authoring:ROOT:overview.adoc[Documentation Authoring and Publishing Guide].


== Project and community

[.project-docs-list]
--
****
xref:{lang}@social-contract:ROOT:social-contract.adoc[Social Contract]

Code for democratic guarantees and open collaboration.
// This is the social contract that all members of the Decidim project are committed to follow.
****

****
xref:{lang}@features:ROOT:general-description.adoc[Functions and Features]

How Decidim works, a detailed feature description, and the roadmap for 2017/2018.
****


****
xref:{lang}@whitepaper:ROOT:decidim-a-brief-overview.adoc[Decidim's White Paper]

Decidim: Political and Technopolitical Networks for Participatory Democracy [_Work-in-progress_].
****
--


== Software manuals

[.software-docs-list]
--
****
xref:{lang}@deploy-and-admin:ROOT:get-decidim.adoc[Software deploy and administration]

Create and run an instance of Decidim for your city, organization or community.
****

****
xref:{lang}@develop:ROOT:introduction.adoc[Developers' Manual]

A description of how Decidim works at the technical level and guidelines for developers.
****
--


== Publications

=== Scientific papers

* Aragón, P., Kaltenbrunner, A., Calleja-López, A., Pereira, A., Monterde, A., Barandiaran, X. E., & Gómez, V. (2017).
  http://arxiv.org/abs/1707.06526[Deliberative Platform Design: The Case Study of the Online Discussions in Decidim Barcelona].
  ArXiv:1707.06526.


=== Dissemination articles, interviews and opinion

* Barandiaran, X. E., Monterde, A., & Pin, G. (2016).
  http://programarilliure.xarxaip.cat/18.html[Decidim.barcelona: autonomia, participació i programari lliure].
  In Xarxaip (Ed.), Programari lliure i de codi obert-Societat lliure i govern obert. (pp. 31–32).
  Barcelona.
